use_frameworks!
platform :ios, '13.0'

target 'EmojiSelectorView_Example' do
  pod 'EmojiSelectorView', :path => '../'
end

target 'EmojiSelectorView_Tests' do
  pod 'EmojiSelectorView', :path => '../'
end
